### PR TITLE
Support for serviceable for packages

### LINKED ISSUE #110: XML validation exception for .Net Core dev packages
**Type**: Bug

**NPE version**: 3.16.0.0

**Installed from**: ClickOnce, current master on GitHub

When opening a package (for example, System.Linq) from https://dotnet.myget.org/F/dotnet-core/, the application crashes due to the following exception:

```
System.InvalidOperationException: The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd' has invalid child element 'serviceable' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd'. List of possible elements expected: 'dependencies, frameworkAssemblies, language, developmentDependency, tags, references, summary' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd'.
   at NuGet.Manifest.<>c.<ValidateManifestSchema>b__26_0(Object sender, ValidationEventArgs e) in E:\Users\Svick\git\NuGetPackageExplorer\Core\Authoring\Manifest.cs:line 275
   at System.Xml.Schema.XNodeValidator.ValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(ValidationEventHandler eventHandler, Object sender, XmlSchemaValidationException e, XmlSeverityType severity)
   at System.Xml.Schema.XmlSchemaValidator.ElementValidationError(XmlQualifiedName name, ValidationState context, ValidationEventHandler eventHandler, Object sender, String sourceUri, Int32 lineNo, Int32 linePos, XmlSchemaSet schemaSet)
   at System.Xml.Schema.XmlSchemaValidator.ValidateElementContext(XmlQualifiedName elementName, Boolean& invalidElementInContext)
   at System.Xml.Schema.XmlSchemaValidator.ValidateElement(String localName, String namespaceUri, XmlSchemaInfo schemaInfo, String xsiType, String xsiNil, String xsiSchemaLocation, String xsiNoNamespaceSchemaLocation)
   at System.Xml.Schema.XNodeValidator.ValidateElement(XElement e)
   at System.Xml.Schema.XNodeValidator.ValidateNodes(XElement e)
   at System.Xml.Schema.XNodeValidator.ValidateElement(XElement e)
   at System.Xml.Schema.XNodeValidator.ValidateNodes(XElement e)
   at System.Xml.Schema.XNodeValidator.ValidateElement(XElement e)
   at System.Xml.Schema.XNodeValidator.Validate(XObject source, XmlSchemaObject partialValidationType, Boolean addSchemaInfo)
   at System.Xml.Schema.Extensions.Validate(XDocument source, XmlSchemaSet schemas, ValidationEventHandler validationEventHandler, Boolean addSchemaInfo)
   at System.Xml.Schema.Extensions.Validate(XDocument source, XmlSchemaSet schemas, ValidationEventHandler validationEventHandler)
   at NuGet.Manifest.ValidateManifestSchema(XDocument document, String schemaNamespace) in E:\Users\Svick\git\NuGetPackageExplorer\Core\Authoring\Manifest.cs:line 270
   at NuGet.Manifest.ReadFrom(Stream stream) in E:\Users\Svick\git\NuGetPackageExplorer\Core\Authoring\Manifest.cs:line 118
   at NuGet.ZipPackage.EnsureManifest() in E:\Users\Svick\git\NuGetPackageExplorer\Core\Packages\ZipPackage.cs:line 224
   at NuGet.ZipPackage..ctor(String filePath) in E:\Users\Svick\git\NuGetPackageExplorer\Core\Packages\ZipPackage.cs:line 38
   at NuGet.MachineCache.FindPackage(String packageId, SemanticVersion version) in E:\Users\Svick\git\NuGetPackageExplorer\Core\Repositories\MachineCache.cs:line 52
   at PackageExplorer.MainWindow.<OpenPackageFromRepository>d__47.MoveNext() in E:\Users\Svick\git\NuGetPackageExplorer\PackageExplorer\MainWindow.xaml.cs:line 299
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PackageExplorer.MainWindow.<OpenFeedItem_Click>d__45.MoveNext() in E:\Users\Svick\git\NuGetPackageExplorer\PackageExplorer\MainWindow.xaml.cs:line 253
```

### PR DESCRIPTION
**Pull request by svick**
Fixes #110

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks! But i guess we need also gui options for these?

**Comment by svick** [comment]
I just wanted to make sure NPE does not crash. But I guess adding it to GUI makes sense, so I did that. I hope I didn't miss any place where I need use the new property.

**Comment by 304NotModified** [comment]
Great work!

**Comment by 304NotModified** [comment]
Published in 3.17! (Clickonce is live, Chocolaty in pipeline)

Thanks!

**Pull request merged**
