### PR TITLE
Shows Assemly information when opening package via double click

### PR DESCRIPTION
**Pull request by jjdotcc**
This should fix issue #22. Should the empty try catch also be removed as that was hiding the error?

### CODE REVIEW

**Comment by 304NotModified** [comment]
Cool! Great work!

Yes remove also the try catch please :)

**Comment by jjdotcc** [comment]
Done ;)

**Comment by 304NotModified** [comment]
thx! testing now!

**Comment by 304NotModified** [comment]
works! Thanks!

**Pull request merged**
