### PR TITLE
Support listing and downloading packages when credentials are provided in URL

### PR DESCRIPTION
**Pull request by Sam13**
Here's a basic implementation of supporting private feeds.
Credentials can be provided within the URL (http://user:pwd@feedUrl). 
Not very secure and no UI support but did the job for me.
Feel free to improve

Thanks
Sam

### CODE REVIEW

**Comment by 304NotModified** [comment]
Cool! Any idea if I could test it somewhere?

**Comment by Sam13** [comment]
Unfortunately I have nothing public for testing.
Maybe you can setup a NuGet server (e.g. Nexus OSS) and create a private feed there?

**Comment by 304NotModified** [comment]
I cannot test this, but I think it's good!

Will merge this (by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/148)

**Comment by Sam13** [comment]
@304NotModified Glad to hear, thanks!

**Comment by 304NotModified** [comment]
@Sam13 I hope you don't have these problems: #98 , #157 

(if not, let us know  - thx!)

**Comment by Sam13** [comment]
@304NotModified Can't confirm those. Latest version with click one installer successfully launched

**Pull request closed without merging**
