### PR TITLE
Un-caps menu

### PR DESCRIPTION
**Pull request by benaadams**
I think this is right? Don't know Xaml very well

Resolves https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/190

### CODE REVIEW

**Comment by NickCraver** [comment]
I THINK THIS IS A FANTASTIC CHANGE

:shipit:

**Comment by terrajobst** [comment]
~~I THINK THIS IS A FANTASTIC CHANGE~~

I think this is a fantastic change.

**Comment by NickCraver** [comment]
~~~I think this is a fantastic change.~~~

NOT YET

**Comment by terrajobst** [comment]
~~NOT YET~~

Now it is.

**Pull request merged**
