### PR TITLE
  #359

### PR DESCRIPTION
**Pull request by Bhaal22**
When iterating over GetFiles, the iterator type is PackageFile not PhysicalPackageFile.
Only f::_file is of type PhysicalPackageFile

How to reproduce the issue:

```
cd c:\tmp
mkdir nuget\binDebug

touch nuget\binDebug\file.txt

cp MyPackage.1.0.0.zip c:\tmp\nuget
unzip MyPackage.1.0.0.zip 
```

Now, open the nuspec with the NugetExplorer 4.x and Save the metadata.

The files xml section moved from:

```
<file src="binDebug\file.txt" target="content\file.txt" />
```

to

```
<file src="content\file.txt" target="content\file.txt" />
```

then the package does not open anymore or nuget pack complains because the src does not match the directory hierarchy.

[MyPackage 1.0.0.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/1763826/MyPackage.1.0.0.zip)

### CODE REVIEW

**Comment by onovotny** [comment]
Can you please provide a repro...a before/after so I can see the difference?

**Comment by Bhaal22** [comment]
@onovotny did you reproduce the issue?

**Comment by onovotny** [comment]
Yes, I can see it. Question though, can the `as` ever return null; should it be using a null check? And If the extension method is no longer used (which it isn't in this case), can you please remove it?

**Comment by Bhaal22** [comment]
I think the PR is not fully reliable. I will check to make to more "generic". I come back to you asap.

**Comment by c0pp3rt0p** [comment]
I don't think this PR is going to fix the issue.  The underlying concrete type is already a PackageFile type in my testing so explicity casting to it does nothing.  The extension method being used is trying to convert to a PackageFileBase which PackageFile is not a descendant of so the conversion results in null.

**Comment by Bhaal22** [comment]
The initial parent commit is:
d9d37f8ff097299b11c0a2e0ffb966d7d14d8d72

@c0pp3rt0p  I just doubler checked. The PR was definitely working when it has been done. 
With last source code version, indeed it does not work anymore.

**Comment by c0pp3rt0p** [comment]
@Bhall22 Cheers, thanks for double checking.

**Comment by c0pp3rt0p** [comment]
My hack to get through the day...  Moved the IEditablePackageFile interface to the Types project as well.

`
using NuGet.Packaging;

namespace NuGetPe
{
    public static class PackageFileExtensions
    {
        public static string OriginalPath(this IPackageFile packageFile)
        {
            if (packageFile is IEditablePackageFile)
                return (packageFile as IEditablePackageFile)?.OriginalPath;
            else
                return (packageFile as PackageFileBase)?.OriginalPath;
        }
    }
}
`

**Comment by onovotny** [comment]
Closing due to age. Please re-open if still applicable and confirmed working.

**Pull request closed without merging**
