### PR TITLE
Add standard .gitattributes + normalize line-endings

### PR DESCRIPTION
**Pull request by caioproiete**
Commit #1 adds standard .gitattributes to normalize line-endings for all contributors moving forward
Commit #2 normalizes the line-endings of all text files to agree with the .gitattributes file added

### CODE REVIEW

**Comment by 304NotModified** [comment]
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/20/files?w=1

**Comment by 304NotModified** [comment]
I think we should exclude the folders which has always binaries? (eg lib)

**Comment by caioproiete** [comment]
Hey Julian,

These assemblies are being referenced directly in the .csproj:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/PackageExplorer.csproj#L104-L112

What do you have in mind? Replace these with NuGet package references?

I'm not familiar with these 3 libraries, but looks like there are NuGet packages for them:

* [GrayscaleEffect](https://www.nuget.org/packages/GrayscaleEffect/)
* [AvalonEdit](https://www.nuget.org/packages/AvalonEdit/)
* [Ookii.Dialogs](https://www.nuget.org/packages/Ookii.Dialogs/)

Do you or @dsplaisted know if these are the right ones?

/cc @304NotModified

---

ps: Not sure what is the relation with this PR though... Maybe open a separate issue/PR? I'm happy to do it.

**Comment by 304NotModified** [comment]
This has been merged. Thanks!

**Pull request merged**
