### PR TITLE
update version to 3.25

### PR DESCRIPTION
**Pull request by 304NotModified**
@onovotny 

any idea if this update also the version in the about?

image

That was first in the commonAssemblyInfo.cs afaik

### CODE REVIEW

**Comment by 304NotModified** [comment]
PS: we need to update https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/README-developers.md

**Comment by onovotny** [comment]
It should be automatic based on the `version.json` file since that updates the assemblies and the dialog gets its version from there: https://github.com/onovotny/NuGetPackageExplorer/blob/ba06c34fbabef2fbe1cb63f03296fadb9332cebc/PackageExplorer/AboutWindow.xaml.cs#L34

**Comment by 304NotModified** [comment]
OK, thx!

**Comment by onovotny** [comment]
was there a reason this wasn't merged?

**Comment by 304NotModified** [comment]
I didn't update the version.json, therefor I closed this one ;)

**Pull request merged**
