### PR TITLE
A quick fix for "Holds onto file handle on file close #145"

### LINKED ISSUE #145: Holds onto file handle on file close
- Bug
- 3.19
- ClickOnce

In case of a BUG:

- What is the current result?
Close file, still keeps the file handle open on the file. Jump into the command prompt and try to delete or move the file.

del : Cannot remove item C:\Development\Logging.1.0.0.nupkg: The process cannot access the file 'C:\Development\Logging.1.0.0.nupkg'
because it is being used by another process.

- What is the expected result?
Close file closes the file handler.

- Are there any work arrounds?
Close NuGet Package Explorer

- Is there a version in which it did worked? 
Not sure

- Is there a package on Nuget.org which shows the bug?
Any

### PR DESCRIPTION
**Pull request by petterlabraaten**
A quick fix for "Holds onto file handle on file close #145"

### CODE REVIEW

**Comment by 304NotModified** [comment]
This will fix the open stream on close of NPE isn't it?

**Comment by petterlabraaten** [comment]
The question is for me? (I'm new to this). Yes. It fixes the problem where "File Handles" (Streams) are left unclosed when a local package is opened and then closed; preventing users from modifying/moving/deleting that packages without fully shutting down NPE.

**Comment by 304NotModified** [comment]
Thanks, will test it!

**Comment by 304NotModified** [comment]
Works great!

**Comment by 304NotModified** [comment]
Also tested with a large package (for https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/87)  of 333MB. Works also well

**Comment by 304NotModified** [comment]
Fixes https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/145

**Pull request merged**
