### PR TITLE
Uno.NPE Fluent Alignment

### PR DESCRIPTION
**Pull request by lukeblevins**
- Update to latest Fluent UI symbols font
- Improvements to control styles
- Tweak typography and colors
- Switch to MUX Expander, NavigationView, and InfoBadge controls
- Remove hardcoded splash color
- Remove unused Uno platform projects

Untitled

### CODE REVIEW

**Comment by lukeblevins** [comment]
Tagging @jeromelaban and @sasakrsmanovic

**Comment by lukeblevins** [comment]
Looks like sln file was somehow messed up so the CI is failing. Investigating this now.

**Comment by MartinZikmund** [comment]
There is yet another version of the new icon font - please use that one 😀 - https://github.com/unoplatform/uno/pull/9815

**Comment by MartinZikmund** [comment]
I will be updating Uno.Fonts tomorrow with this version, but for now you can grab it from the PR directly . If fixes alignment and clipping on WASM

**Comment by jeromelaban** [comment]
Closed in favor of https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/1539

**Pull request closed without merging**
