### PR TITLE
add .NET 4.7 + 4.71, remove 4.6.3

### PR DESCRIPTION
**Pull request by 304NotModified**
or is there a 4.6.3?

(see https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs)

@onovotny what's the next version number? 

fixes https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/206

### CODE REVIEW

**Comment by onovotny** [comment]
There's 4.6.2, 4.7 and 4.7.1

**Comment by 304NotModified** [comment]
> @onovotny what's the next version number

I meant for npe  ;). Can't see a version number in the windows store. Is it 3.25?

**Comment by onovotny** [comment]
3.25 should be the next version: 
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer.Package/package.appxmanifest#L3

**Comment by 304NotModified** [comment]
ok, thanks!

**Pull request merged**
