### PR TITLE
Centennial support 

### PR DESCRIPTION
**Pull request by onovotny**
This is a PR to implement Centennial support for distributing NPE via the Windows Store.

Addresses #15 

Current Status:
Project builds, deploys and works on local machine. File type associations work and you can double-click nuspec/nupkg

To Do:
- [x] Convert icon assets to supported formats (png)
- [x] Store association of Win8 app

There were no code changes to NPE itself. Only a new packaging project was created for the store identity.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Hey thanks for this!

Did you got my gitter messages?

Could you guide me in testing and releasing it?

**Comment by onovotny** [comment]
Just responded in the gitter

**Comment by onovotny** [comment]
@304NotModified what would you want to see in the docs for that? There's not much anyone else can do with it right now :/

The steps for me are simply "get latest from the release label", update version in the packaging manifest, create store package, update store listing with appxupload file and release notes.

**Comment by 304NotModified** [comment]
> @304NotModified what would you want to see in the docs for that? There's not much anyone else can do with it right now :/

Well every (future) maintainer should have a check list to follow IMO. Finding out how to update the ClickOnce package took me hours. 



> The steps for me are simply "get latest from the release label", update version in the packaging manifest, create store package, update store listing with appxupload file and release notes.

LOL - I even don't know how to do this. I have never used Windows Store before ;)

**Pull request merged**
