### PR TITLE
Package project

### PR DESCRIPTION
**Pull request by onovotny**
Updates to VS 2017 and simplifies the projects. Also uses the new packaging project in VS 2017 15.4 for the Windows Store

### CODE REVIEW

**Comment by 304NotModified** [comment]
👍 

AppVeyor is still using msbuild 14 I see. I think we need at least `image: Visual Studio 2017`

**Comment by onovotny** [comment]
Will add that

**Comment by 304NotModified** [comment]
Please double check the artifacts in AppVeyor. (master build: https://ci.appveyor.com/project/NuGetPackageExplorer/nugetpackageexplorer/build/3.23.0.313/artifacts)

thx!

**Comment by 304NotModified** [comment]
did the build moved from 30s -> 2 minutes?

(see https://ci.appveyor.com/project/NuGetPackageExplorer/nugetpackageexplorer/history)

**Comment by onovotny** [comment]
The VS preview images are on slower hosts

**Comment by 304NotModified** [comment]
> The VS preview images are on slower hosts

On AppVeyor? Really? That's :(

**Comment by onovotny** [comment]
Artifacts should be good now.

**Comment by 304NotModified** [comment]
is the changed (version) name on purpose?

**Comment by onovotny** [comment]
The versions are automated now. They only have the git hash on non-release branches like PRs. The definition of release branch is in the version.json.

**Comment by 304NotModified** [comment]
👍

**Comment by onovotny** [comment]
Good to merge?

**Comment by 304NotModified** [comment]
Yes :)

**Pull request merged**
