### PR TITLE
Fix credentials + fallback for legacy API

### PR DESCRIPTION
**Pull request by rikoe**
I created these changes in 2014 when I was trying to fix NuGetPackageExplorer to work with a local Active Directory install of ProGet.

The changes were both to be able to download packages from and push packages to the server using Windows Integrated Authentication, as supported by ProGet.

Please review and approve/discard as you see fit - hopefully we can address #16 and #4 with this.

### CODE REVIEW

**Comment by 304NotModified** [comment]
:)  thanks! 

Will try to release this week a new version.

**Comment by sbochoa** [comment]
@rikoe Hello thanks for this change but what about if im not in the domain is there a chance to popup a login dialog to enter the credentials just like visual studio does?

**Comment by rikoe** [comment]
Well, you'd need to be clear about your use case. When would you use
NugetPackageExplorer and not be in the domain already?

My fix was simply for authenticating against the NuGet server with the same
credentials you are already logged in with. It's just a few lines of code
to enable capturing the user's current credentials.

What you're asking for sounds a lot more complex, effectively supporting
multiple modes of authentication. Also keep in mind that the Visual Studio
dialog you are referring to is actually quite a lot more complex than it
first appears. It is hosting a browser control that authenticates against a
hosted OAuth security provider as far as I know (if we are referring to the
same one).

If you really need what you are asking for I would suggest opening a
separate issue for it describing exactly what you are authenticating
against and how (maybe with screenshots).

We can then try and prioritise it, but if it's not a common use case you
may need to fork it and try yourself! :-)

**Comment by 304NotModified** [comment]
@rikoe is this PR better than https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/48?

**Comment by rikoe** [comment]
It is a superset of #48 - it includes the same change to PackageDownloader.cs, but adds default credentials in a bunch of other places.

The one additional thing it does, is that (at the time) ProGet used a legacy NuGet API for searching packages by id, which didn't work with NuGetPackageExplorer, so I added some code to fall back to the legacy API

**Comment by 304NotModified** [comment]
Fixes https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/4

**Comment by WiteCastle** [comment]
How would one authenticate with a VSO nuget feed? https://blogs.msdn.microsoft.com/visualstudioalm/2015/08/27/announcing-package-management-support-for-vsotfs/

**Comment by 304NotModified** [comment]
Hi @WiteCastle , only Windows authentication (without login form) is currently supported. 

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/92

**Pull request merged**
